d <-read.table("./household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data <- subset(d, d$Date == "1/2/2007" | d$Date == "2/2/2007")
rm(d)
png(filename = "plot1.png", width = 480, height = 480)
hist(as.numeric(data$Global_active_power), col="red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()